### ISSUE TITLE
Crash on reading "calculus"

### ISSUE THREAD

**Issue by gvanem** [g0orx/wdsp#18]
This WDSP library was recently added to [Quisk](https://pypi.org/project/quisk/#files).

But using `libwdsp.dll` in Quisk crashes in `emnr.c`:
```c
  a->g.fileb = fopen("calculus", "rb");
  fread(a->g.GG, sizeof(double), 241 * 241, a->g.fileb);
```

Absolutely no check for a non-NULL `a->g.fileb`.
But why cannot `_WIN32` code use the generated `calculus.c` data too?
Works fine with Quisk.

**Comment by g0orx** [comment]
I suspect the dll with with Quisk is the Windows DLL from either PowerSDR or Thetis which are Windows applications.  This code is a port of that version of WDSP for Linux. I have never tried compiling this version on Windows as I do not have any Windows development environment.,  The widows version uses a file to load the calculus data. I decided for the Linux version to create the calculus.c file so that it does not require an additional file.
If you want to try compiling this code on Windows and making the change to use the file then feel free to do so.

-- John

**Comment by gvanem** [comment]
> I suspect the dll with with Quisk is the Windows DLL from either PowerSDR

No. I built it myself.

> I suspect the dll with with Quisk is the Windows DLL from either PowerSDR

Done that. But I suspect there is another more Windows-friendly repo for WDSP. Not sure where I should put my effort.

**Comment by g0orx** [comment]
The original Windows version of WDSP can be found in https://github.com/TAPR/OpenHPSDR-Thetis/tree/master/Project%20Files/Source/wdsp.

I did not write the code to generate the C code from the calculus file and have never used it.  The original file was part of the WDSP Windows code which I manually changed to the C code.  Warren generated the original file.

**Comment by dl1ycf** [comment]
Well I think the file "calculus.c" was added when porting WDSP to linux. It simply contains the data in the binary file "calculus". To be absolutely sure about that, I added the file "make_calculus.c" a while ago which generates the file "calculus.c" from the file "calculus", so one can generate a new calculus.c file should the binary file calculus be modified upstream. Note this one can only do on a machine with the same "endian" kind as the orginal (Windows) CPU, but once calculus.c has been generated, it works for both "endians".

Of course, using the data as static data (as done here), is absolutely to be preferred also on Window, but the point is simply the don't do it there (look at the TAPR repo). So on Linux an MacOS, the data is simply copied from the static array GG[] and GGS[]. To this end, calculus.h must be included which defines them as external, and calculus.c must be compiled and linked into WDSP.

So what I do not understand is why you complain about Windows probleme HERE, where they have been solved by John.
But I am sure you can use the code here in Windows as well, simply modify emnr.c as to include calculus.h
and activate the "copy" code rather than the "read" code.

Yours DL1YCF.

**Comment by gvanem** [comment]
> and activate the "copy" code rather than the "read" code.

How about using `GG[]` and `GGS[]` in-place instead. Like:
```diff
--- a/emnr.c 2021-12-22 13:33:17
+++ b/emnr.c 2021-12-23 14:58:38
@@ -275,20 +272,18 @@
        //
+#ifdef USE_CALCULUS_IN_PLACE
+   a->g.GG = GG;
+   a->g.GGS = GGS;
+#else
        a->g.GG = (double *)malloc0(241 * 241 * sizeof(double));
        a->g.GGS = (double *)malloc0(241 * 241 * sizeof(double));
         memcpy(a->g.GG, GG, 241 * 241 * sizeof(double));
         memcpy(a->g.GGS, GGS, 241 * 241 * sizeof(double));
 #endif

        a->np.incr = a->incr;
        a->np.rate = a->rate;
@@ -447,8 +442,10 @@
        _aligned_free(a->np.alphaOptHat);
        _aligned_free(a->np.p);

+#ifndef USE_CALCULUS_IN_PLACE
        _aligned_free(a->g.GGS);
        _aligned_free(a->g.GG);
+#endif
        _aligned_free(a->g.prev_mask);
        _aligned_free(a->g.prev_gamma);
        _aligned_free(a->g.lambda_d);
@@ -684,7 +681,7 @@
        memcpy (a->mask + n, a->ae.nmask, (a->ae.msize - 2 * n) * sizeof (double));
 }

-double getKey(double* type, double gamma, double xi)
+double getKey(const double* type, double gamma, double xi)
 {
        int ngamma1, ngamma2, nxi1, nxi2;
        double tg, tx, dg, dx;
```

The alignment of these arrays should be OK.

**Comment by dl1ycf** [comment]
If these are „read-only“ then you are right no copy is necessary,
and it is sufficient to copy the start addresses and not the
contents of GG and GGS. The „copy“ has been done (I guess) to
minimize the change w.r.t. the Windows version.

But this is „decoration“, my question is whether your problems
are solved now?
